# Generated by Django 5.2.9 on 2026-01-06 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='视频ID')),
                ('nickname', models.CharField(max_length=100, verbose_name='作者昵称')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='视频描述')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('duration', models.CharField(blank=True, max_length=20, null=True, verbose_name='视频时长')),
                ('follower_count', models.IntegerField(default=0, verbose_name='粉丝数')),
                ('digg_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('comment_count', models.IntegerField(default=0, verbose_name='评论数')),
                ('collect_count', models.IntegerField(default=0, verbose_name='收藏数')),
                ('share_count', models.IntegerField(default=0, verbose_name='分享数')),
                ('download_count', models.IntegerField(default=0, verbose_name='下载数')),
            ],
            options={
                'verbose_name': '视频信息',
                'db_table': 'tb_video',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='评论ID')),
                ('nickname', models.CharField(max_length=100, verbose_name='用户昵称')),
                ('content', models.TextField(verbose_name='原始评论')),
                ('content_clean', models.TextField(verbose_name='清洗后评论')),
                ('create_time', models.DateTimeField(verbose_name='评论时间')),
                ('ip_label', models.CharField(max_length=50, verbose_name='IP属地')),
                ('digg_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('sentiment_score', models.FloatField(default=0.5, verbose_name='情感得分')),
                ('sentiment_label', models.CharField(max_length=10, verbose_name='情感标签')),
                ('hour', models.IntegerField(default=0, verbose_name='发布小时')),
                ('text_len', models.IntegerField(default=0, verbose_name='评论长度')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='douyin_hangxi.video', verbose_name='所属视频')),
            ],
            options={
                'verbose_name': '评论情感分析',
                'db_table': 'tb_comment',
            },
        ),
    ]
