# Generated by Django 5.2.9 on 2026-01-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('douyin_hangxi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(help_text='例如: V1.0_RandomForest', max_length=50, verbose_name='模型版本号')),
                ('model_file', models.FileField(upload_to='ai_models/', verbose_name='模型权重文件 (.pkl)')),
                ('scaler_file', models.FileField(upload_to='ai_models/', verbose_name='数据标准化器 (.pkl)')),
                ('is_active', models.BooleanField(default=False, help_text='选中此项将立即切换系统使用的模型', verbose_name='当前激活')),
                ('description', models.TextField(blank=True, verbose_name='更新日志/备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': 'AI 模型资产中心',
                'verbose_name_plural': 'AI 模型资产中心',
                'db_table': 'tb_ai_config',
            },
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '评论舆情管理', 'verbose_name_plural': '评论舆情管理'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': '视频数据管理', 'verbose_name_plural': '视频数据管理'},
        ),
    ]
