# Generated by Django 5.2.9 on 2026-01-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('douyin_hangxi', '0002_aimodelconfig_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='actual_vs_predicted_error',
            field=models.FloatField(blank=True, null=True, verbose_name='预测偏差率(%)'),
        ),
        migrations.AddField(
            model_name='video',
            name='audio_bpm',
            field=models.IntegerField(blank=True, null=True, verbose_name='背景音乐BPM'),
        ),
        migrations.AddField(
            model_name='video',
            name='cut_frequency',
            field=models.FloatField(blank=True, null=True, verbose_name='镜头切换频率'),
        ),
        migrations.AddField(
            model_name='video',
            name='predicted_digg_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='模型预测点赞数'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/%Y%m%d/', verbose_name='视频素材'),
        ),
        migrations.AddField(
            model_name='video',
            name='visual_brightness',
            field=models.FloatField(blank=True, null=True, verbose_name='平均亮度'),
        ),
        migrations.AddField(
            model_name='video',
            name='visual_saturation',
            field=models.FloatField(blank=True, null=True, verbose_name='色彩饱和度'),
        ),
    ]
