# Generated by Django 5.2.9 on 2026-01-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('douyin_hangxi', '0003_video_actual_vs_predicted_error_video_audio_bpm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='theme_label',
            field=models.CharField(default='默认主题', max_length=100, verbose_name='所属主题/离线包'),
        ),
        migrations.AddField(
            model_name='video',
            name='theme_label',
            field=models.CharField(default='默认主题', max_length=100, verbose_name='所属主题/离线包'),
        ),
        migrations.AlterField(
            model_name='aimodelconfig',
            name='description',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='aimodelconfig',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='当前激活'),
        ),
        migrations.AlterField(
            model_name='aimodelconfig',
            name='model_file',
            field=models.FileField(upload_to='ai_models/', verbose_name='权重文件'),
        ),
        migrations.AlterField(
            model_name='aimodelconfig',
            name='scaler_file',
            field=models.FileField(upload_to='ai_models/', verbose_name='标准化器'),
        ),
        migrations.AlterField(
            model_name='aimodelconfig',
            name='version_name',
            field=models.CharField(max_length=50, verbose_name='模型版本号'),
        ),
    ]
