# Generated by Django 5.2.9 on 2026-01-11 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('douyin_hangxi', '0004_comment_theme_label_video_theme_label_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aimodelconfig',
            options={'verbose_name': 'AI预测模型管理', 'verbose_name_plural': 'AI预测模型管理'},
        ),
        migrations.AlterField(
            model_name='aimodelconfig',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='aimodelconfig',
            name='description',
            field=models.TextField(blank=True, verbose_name='备注说明'),
        ),
        migrations.AlterField(
            model_name='aimodelconfig',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='当前使用中'),
        ),
        migrations.AlterField(
            model_name='aimodelconfig',
            name='model_file',
            field=models.FileField(upload_to='ai_models/', verbose_name='模型权重文件'),
        ),
        migrations.AlterField(
            model_name='aimodelconfig',
            name='scaler_file',
            field=models.FileField(upload_to='ai_models/', verbose_name='数据标准化文件'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='原始评论内容'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content_clean',
            field=models.TextField(verbose_name='清洗后内容'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='theme_label',
            field=models.CharField(default='默认主题', max_length=100, verbose_name='所属主题包'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='douyin_hangxi.video', verbose_name='所属视频'),
        ),
        migrations.AlterField(
            model_name='video',
            name='actual_vs_predicted_error',
            field=models.FloatField(blank=True, null=True, verbose_name='预测偏差率'),
        ),
        migrations.AlterField(
            model_name='video',
            name='audio_bpm',
            field=models.IntegerField(blank=True, null=True, verbose_name='音频节奏BPM'),
        ),
        migrations.AlterField(
            model_name='video',
            name='cut_frequency',
            field=models.FloatField(blank=True, null=True, verbose_name='平均剪辑频率'),
        ),
        migrations.AlterField(
            model_name='video',
            name='predicted_digg_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='预测点赞数'),
        ),
        migrations.AlterField(
            model_name='video',
            name='theme_label',
            field=models.CharField(default='默认主题', max_length=100, verbose_name='所属主题包'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/%Y/%m/%d/', verbose_name='视频原文件'),
        ),
        migrations.AlterField(
            model_name='video',
            name='visual_brightness',
            field=models.FloatField(blank=True, null=True, verbose_name='画面亮度'),
        ),
        migrations.AlterField(
            model_name='video',
            name='visual_saturation',
            field=models.FloatField(blank=True, null=True, verbose_name='画面饱和度'),
        ),
        migrations.AlterModelTable(
            name='aimodelconfig',
            table='tb_ai_model_config',
        ),
    ]
