# Generated by Django 5.2.9 on 2026-02-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('douyin_hangxi', '0005_alter_aimodelconfig_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='analysis_status',
            field=models.IntegerField(default=0, verbose_name='AI分析状态'),
        ),
        migrations.AddField(
            model_name='video',
            name='local_temp_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='本地临时路径'),
        ),
    ]
