# Generated by Django 5.2.9 on 2026-02-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('douyin_hangxi', '0006_video_analysis_status_video_local_temp_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='analysis_status',
            field=models.IntegerField(db_index=True, default=0, verbose_name='AI分析状态'),
        ),
        migrations.AlterField(
            model_name='video',
            name='theme_label',
            field=models.CharField(db_index=True, default='默认主题', max_length=100, verbose_name='所属主题包'),
        ),
    ]
