# Generated by Django 5.2.9 on 2026-02-27 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('douyin_hangxi', '0007_alter_video_analysis_status_alter_video_theme_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llm_api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='大模型API Key')),
                ('llm_model_name', models.CharField(default='ernie-4.0-8k', max_length=50, verbose_name='大模型名称')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '创作者配置',
                'verbose_name_plural': '创作者配置',
                'db_table': 'tb_creator_config',
            },
        ),
    ]
